# Generated by Django 3.0.3 on 2020-04-01 00:54

import api.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mymodel_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='json',
            field=api.fields.JSONField(),
        ),
        migrations.AlterField(
            model_name='sale',
            name='items',
            field=api.fields.JSONField(default=object),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_intent',
            field=api.fields.JSONField(default=dict),
        ),
    ]
